# Generated by Django 3.2.4 on 2021-06-27 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_uzer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Uzer',
        ),
    ]
